### ISSUE TITLE
isuuse when implementing in fragment instead of Activity

### ISSUE THREAD

**Issue by bliveinhack** [kaedea/Andriod-Seamless-ViewPager-Header#1]
Hi, I've followed your code. but it looks like i need some fixes in listener. i am unable to write this using fragment instead of Activity. may be context issue. 

i'm getting class cast exception on 

 try {
            mListener = (ScrollableFragmentListener) activity;
        } catch (ClassCastException e) {
            throw new ClassCastException(
                    activity.toString() + " must implement ScrollableFragmentListener");
        }

Please help.
Thanks for sharing your code.

**Comment by kaedea** [comment]
please offer me the exception printstack

**Comment by bliveinhack** [comment]
05-13 17:31:08.983: E/AndroidRuntime(508): FATAL EXCEPTION: main
05-13 17:31:08.983: E/AndroidRuntime(508): java.lang.ClassCastException: com.njoyful.userapp.Activity.MainActivity@41cff1c0 must implement ScrollableFragmentListener
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.njoyful.userapp.Fragments.DashBordCategoryFragment.onAttach(DashBordCategoryFragment.java:183)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:903)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:842)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.app.Fragment.setUserVisibleHint(Fragment.java:859)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.app.FragmentPagerAdapter.setPrimaryItem(FragmentPagerAdapter.java:130)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.view.ViewPager.populate(ViewPager.java:1071)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:447)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.njoyful.userapp.Fragments.DashbordFragment$2.onResponse(DashbordFragment.java:181)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.njoyful.userapp.Fragments.DashbordFragment$2.onResponse(DashbordFragment.java:1)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.os.Handler.handleCallback(Handler.java:615)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.os.Handler.dispatchMessage(Handler.java:92)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.os.Looper.loop(Looper.java:137)
05-13 17:31:08.983: E/AndroidRuntime(508):  at android.app.ActivityThread.main(ActivityThread.java:4921)
05-13 17:31:08.983: E/AndroidRuntime(508):  at java.lang.reflect.Method.invokeNative(Native Method)
05-13 17:31:08.983: E/AndroidRuntime(508):  at java.lang.reflect.Method.invoke(Method.java:511)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
05-13 17:31:08.983: E/AndroidRuntime(508):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
05-13 17:31:08.983: E/AndroidRuntime(508):  at dalvik.system.NativeStart.main(Native Method)

**Comment by kaedea** [comment]
Okay, I try to cast MainActivity to ScrollableFragmentListener and it works.

``` java
 ScrollableFragmentListener scrollableFragmentListener = (ScrollableFragmentListener)this;
        if (scrollableFragmentListener!=null){
            Toast.makeText(this,"scrollableFragmentListener cast success",Toast.LENGTH_SHORT).show();
        }
```

is that your MainActivity forget to implements ScrollableFragmentListener

**Comment by kaedea** [comment]
Maybe I will create a MainFragment instead of MainActivity later.

**Comment by bliveinhack** [comment]
No, My Activity is not implementing but my fragment is.

So, what should be the quick fix. for now.

**Comment by kaedea** [comment]
```
try {
mListener = (ScrollableFragmentListener) `activity`;
} catch (ClassCastException e) {
throw new ClassCastException(
activity.toString() + " must implement ScrollableFragmentListener");
}
```

you can not use `activity` here, please use your fragment instance which implements listener

**Comment by bliveinhack** [comment]
ohh...i write.

try {
mListener = (ScrollableFragmentListener) DashBordfragment.newInstance();
} catch (ClassCastException e) {
throw new ClassCastException(
activity.toString() + " must implement ScrollableFragmentListener");
}

and it works. but now i'm getting NPE at

@Override
    public boolean isViewBeingDragged(MotionEvent event) {
        return mScrollableListenerArrays.valueAt(pager.getCurrentItem())
                .isViewBeingDragged(event);
    }

:(

**Comment by kaedea** [comment]
Okay I have find the problem.
Yes it need to do some adjustment when placed in Fragment

**Comment by bliveinhack** [comment]
Great, can i expect the update in #commit or may be in other branch with fragment implementation. or can you please provide me some guide to do it now.

Many thanks.

**Comment by kaedea** [comment]
edit BaseViewPagerFragment.java

```
 @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);
        try {
            mListener = (ScrollableFragmentListener) activity;
        } catch (ClassCastException e) {
            /*throw new ClassCastException(
                    activity.toString() + " must implement ScrollableFragmentListener");*/
        }
    }
```

edit in your MainFragment with you use to replace my MainActivity

```
@Override
    public boolean isViewBeingDragged(MotionEvent event) {
        ScrollableListener listener = mScrollableListenerArrays.valueAt(mViewPager.getCurrentItem());
        if (listener==null)return true;
        return listener.isViewBeingDragged(event);
    }
```

**Comment by kaedea** [comment]
I will make a update to support usage in Fragment.
I will come soon.

**Comment by bliveinhack** [comment]
it working now. Thanks for your help. 
but Scrolling is unexpected behavior. when i scroll from bottom to top header view immediately start scrolling rather than when my Listview is at top position. [may be because of my listview is variable size elements?]. may be you should try with custom adapter to reproduce this behavior.

Thanks.

**Comment by kaedea** [comment]
now add fragment support in the demo
